import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const DOCS_HOST = process.env.NEXT_PUBLIC_DOCS_IP;
  const DOCS_PORT = process.env.NEXT_PUBLIC_DOCS_PORT;

  const docsUrl = `http://${DOCS_HOST}:${DOCS_PORT}`;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Truck Agent World!
        </h1>

        <p className={styles.description}>
          Check out our docs <a href={docsUrl}>HERE</a>
        </p>

        <p className={styles.description}>
        Truck Agent World is an educational tool that allows users to explore and compare different search algorithms. In this application, we have implemented several algorithms, including depth-first search, breadth-first search, and A* search, and have designed a range of challenges and scenarios to demonstrate how these algorithms work and how they can be applied. With in-depth explanations and interactive simulations, Truck Agent World is a valuable resource for anyone interested in learning about search algorithms and their applications. Whether you are a student, researcher, or professional looking to deepen your understanding of these important algorithms, Truck Agent World is an engaging and informative resource. Try it out today and start exploring the world of search algorithms with Truck Agent World!




        </p>

        </main>
    </div>
  )
}
